name: "Next Workflow"
on:
  workflow_run:
    workflows: ["PR Merged"]
    types:
      - completed
jobs:
  next_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Validation du WF suivant"
        run: echo "Le workflow précédent est terminé"
