name: Workflow Depends

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Job 1 exécuté"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Job 2 exécuté après le Job 1"
