name: PR Merged
on:
  pull_request:
    types: [closed]
jobs:
  pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "PR a été mergée"


        